### ISSUE TITLE
No stand alone Win app

### ISSUE THREAD

**Issue by Zeikad** [recleelab/dNEMO-0.9.0#2]
Hi, 
I'm a cell biology PhD student with very limited coding experience, so I wanted to use the Windows standalone version of your project, however, I noticed that the zip file for 'windows' users actually contains the 'Mac' version of the app. Sadly I'm not able to use it then. 

Is it a mistake or the 'windows' version is discontinued? In the later case, is it possible to launch the app with a Runtime of Mathlab instead?

Many thanks in advance,
Best, 

Zeinab

**Comment by gabrieljaykay** [comment]
Thank you for bringing this oversight to our attention -- the Box folder linked to in the description has been updated with the folder that contains the Windows version of the standalone application.
